
#vim /etc/nginx/default.d/roboshop.conf

#systemctl enable nginx
#systemctl start nginx
#systemctl restart nginx

- name: Install nginx
  ansible.builtin.yum:
    name: nginx
    state: latest

- name: Removing old content
  ansible.builtin.file:
    path: /usr/share/nginx/html
    state: absent

- name: Creating application directory
  ansible.builtin.file:
    path: /usr/share/nginx/html
    state: directory
    mode: '0755'

- name: downloading and unzipping the artifacts
  ansible.builtin.unarchive:
    src: https://roboshop-artifacts.s3.amazonaws.com/frontend.zip
    dest: /usr/share/nginx/html
    remote_src: yes

- name: Copy file with owner and permissions
  ansible.builtin.copy:
    src: roboshop.conf
    dest: /etc/nginx/default.d/roboshop.conf

- name: Enable and start the nginx service
  ansible.builtin.systemd:
    name: nginx
    state: restarted
    enabled: yes


