- name: Configure YUM Repos for erlang
  ansible.builtin.shell: curl -s https://packagecloud.io/install/repositories/rabbitmq/erlang/script.rpm.sh | bash

- name: Configure YUM Repos for RabbitMQ
  ansible.builtin.shell: curl -s https://packagecloud.io/install/repositories/rabbitmq/rabbitmq-server/script.rpm.sh | bash

- name: install erlang and RabbitMQ
  ansible.builtin.yum:
    name:
      - erlang
      - rabbitmq-server
    state: installed

- name: Enable and restart rabbitmq-server
  ansible.builtin.service:
    name: rabbitmq-server
    enabled: true
    state: restarted

- name: Add application user
  community.rabbitmq.rabbitmq_user:
    user: robohsop
    password: roboshop123
    vhost: /
    configure_priv: .*
    read_priv: .*
    write_priv: .*
    state: present

